### PR TITLE
Highlights + Hubs fixes

### LINKED ISSUE #663: WEB - all hubs page doesnt always show all hubs

### PR DESCRIPTION
**Pull request by facing-n**
closes #663 #662 #661

### CODE REVIEW

File: js/sdk/src/contexts/Nina/nina.js [hunk 1]
```diff
@@ -833,6 +833,7 @@ const ninaContextHelper = ({
   const getSubscriptionsForUser = async (accountPubkey) => {
     try{
       const { subscriptions } = await NinaSdk.Account.fetchSubscriptions(accountPubkey, false)
+      console.log('subscriptions: ', subscriptions)
```
Comment (ejf89) [inline js/sdk/src/contexts/Nina/nina.js:836]: log

File: js/web/components/ReleaseCreate.js [hunk 2]
```diff
@@ -424,7 +424,12 @@ const ReleaseCreate = () => {
...
   }
-  console.log('wallet?.connected && npcAmountHeld < 1 && (!profileHubs && profileHubs?.length === 0)', wallet?.connected && npcAmountHeld === 0 && (!profileHubs ||  profileHubs?.length === 0))
+  console.log(
+    'wallet?.connected && npcAmountHeld < 1 && (!profileHubs && profileHubs?.length === 0)',
+    wallet?.connected &&
+      npcAmountHeld === 0 &&
+      (!profileHubs || profileHubs?.length === 0)
+  )
   console.log('npcAmountHeld', npcAmountHeld)
   console.log('profileHubs', profileHubs)
```
Comment (ejf89) [inline js/web/components/ReleaseCreate.js:434]: kill logs

**Review by ejf89 — APPROVED** [review]
couple logs to remove but looks good otherwise
