### PR TITLE
Hub fixes

### LINKED ISSUE #397: Big Red Alert that archiving release from Hub doesn't delete the release

### LINKED ISSUE #402: Snackbar says success when Fund Bundlr fails w/ attempted over funding

### LINKED ISSUE #403: Add Check that Bundlr deposit leaves enough SOL for further transactions

### LINKED ISSUE #410: Bug: Hubs / Web - when last track in queue ends pause button should switch back to play

### LINKED ISSUE #411: CTA: Publish after Hub create

### LINKED ISSUE #416: UI: Snackbar for Bundlr balance too low

### PR DESCRIPTION
**Pull request by facing-n**
closes #416
closes #411
closes #403
closes #410 
closes #402 
closes #397

### CODE REVIEW

File: js/hubs/components/HubCreate.js [hunk 1]
```diff
@@ -412,6 +412,15 @@ const HubCreate = ({ update, hubData }) => {
         >
           {`${formValues.hubForm.displayName}  has been created!  View Hub.`}
         </Button>
+        <Button
```
Comment (ejf89) [inline js/hubs/components/HubCreate.js:415]: `marginTop: '15px'` plz

**Review by ejf89 — APPROVED** [review]
button on hub create needs margin but +1
