### PR TITLE
Default feed fix

### LINKED ISSUE #733: FEED - feed should default to nina's feed if no wallet connection

### LINKED ISSUE #740: DASHBOARD - remove play button if no playlist exists

### PR DESCRIPTION
**Pull request by ikjudd**
- Closes #733 
- Closes #740

### CODE REVIEW

File: js/web/components/Feed.js [hunk 1]
```diff
@@ -597,14 +600,503 @@ const Feed = ({
     return feedItemComponents || []
   }, [items, isPlaying, track])
 
+  const defaultFeedItems = useMemo(() => {
```
Comment (ejf89) [inline js/web/components/Feed.js:603]: the set of items should be passed as a prop, this code should not be duplicated

**Review by ejf89 — CHANGES_REQUESTED** [review]
plz correct defaultItems approach

File: js/sdk/src/contexts/Release/release.js [hunk 2]
```diff
@@ -1550,6 +1550,7 @@ const releaseContextHelper = ({
   const getFeedForUser = async (publicKey, offset) => {
     try {
       const { data } = await axios.get(`${process.env.NINA_API_ENDPOINT}/accounts/${publicKey}/feed?offset=${offset}`)
+      console.log('feed', data)
```
Comment (ejf89) [inline js/sdk/src/contexts/Release/release.js:1553]: remove log plz @ikjudd

**Review by ejf89 — APPROVED** [review]
