### PR TITLE
Hubs dashboard UI fix

### LINKED ISSUE #579: HUB - fix hub update bug

### LINKED ISSUE #580: HUBS - 'release created' appears below updated button text

### LINKED ISSUE #582: RELEASES - fix track repost to hub error

### LINKED ISSUE #583: HUBS - add royalty recipient bug

### LINKED ISSUE #584: HUBS - fix publish release bug

### LINKED ISSUE #586: RELEASES - link royalty recipients to their respective profiles

### LINKED ISSUE #589: RELEASE - fix race condition for fetching hubs in AddToHubsModal

### PR DESCRIPTION
**Pull request by ikjudd**
- Closes #579 
- Closes #580 
- Closrd #581 
- Closes #582 
- Closes #583 
- Closes #584 
- Closes #586 
- Closes #589

### CODE REVIEW

**Comment by ejf89** [comment]
Screen Shot 2022-11-11 at 5 42 46 PM

can we fix this so that it doesnt show the PUBLISH RELEASE BUTTON if upload account needs to be funded?

**Comment by ejf89** [comment]
Screen Shot 2022-11-14 at 10 45 04 AM

hubHeader needs some finessing on desktop (name + follow/unfollow beingcut off)

**Comment by ejf89** [comment]
#582 still not working

File: js/hubs/components/HubCreate.js [hunk 1]
```diff
@@ -195,14 +195,10 @@ const HubCreate = ({ update, hubData }) => {
...
+  
     try {
-      const error = checkIfHasBalanceToCompleteAction(
-        NinaProgramAction.HUB_INIT_WITH_CREDIT
-      );
-      if (error) {
-        enqueueSnackbar(error.msg, { variant: "failure" });
-        return;
-      }
+
```
Comment (ejf89) [inline js/hubs/components/HubCreate.js:200]: should add a `checkIfHasBalanceToComplete` for HUB_UPDATE

File: js/hubs/components/ReleaseCreateViaHub.js [hunk 2]
```diff
@@ -208,9 +210,9 @@ const ReleaseCreateViaHub = ({ canAddContent, hubPubkey }) => {
     e.preventDefault();
     try {
       if (releaseCreated) {
-        // router.push({pathname: `/${hubData.handle}/releases/${releaseInfo.hubRelease.toBase58()}`});
+      //  router.push({pathname: `/${hubData.handle}/releases/${releaseInfo.hubRelease.toBase58()}`});
```
Comment (ejf89) [inline js/hubs/components/ReleaseCreateViaHub.js:213]: this can be removed

File: js/sdk/src/contexts/Audio/audio.js [hunk 3]
```diff
@@ -149,7 +149,10 @@ const audioPlayerContextHelper = ({
   currentIndex,
   setTrack,
   track,
+  ninaClient
 }) => {
+  //  const { collection, shouldRemainInCollectionAfterSale, ninaClient } =
```
Comment (ejf89) [inline js/sdk/src/contexts/Audio/audio.js:154]: is this removed on purpose?

File: js/web/components/Release.js [hunk 4]
```diff
@@ -38,23 +38,29 @@ const ReleaseComponent = ({ metadataSsr }) => {
 
   useEffect(() => {}, [releaseState])
 
-  useEffect(() => {
-    if (wallet.connected) {
-      getHubsForUser(wallet.publicKey.toBase58())
-    }
-  }, [wallet.connect])
+  // useEffect(() => {
```
Comment (ejf89) [inline js/web/components/Release.js:41]: remove console logs in file

File: js/web/components/ReleaseCreate.js [hunk 5]
```diff
@@ -247,8 +247,11 @@ const ReleaseCreate = () => {
   }, [track])
 
   const handleSubmit = async () => {
+    console.log('hitty')
```
Comment (ejf89) [inline js/web/components/ReleaseCreate.js:250]: bro

**Review by ejf89 — CHANGES_REQUESTED** [review]
plz address comments

File: js/web/components/ReleaseCreate.js (hunk 5 above)
Comment (ejf89) [reply js/web/components/ReleaseCreate.js:250]: there are additional logs in this file to be cleaned up aswell

File: js/hubs/components/HubOverview.js [hunk 6]
```diff
@@ -47,7 +47,7 @@ const HubOverview = ({ hubPubkey, isAuthority }) => {
         .reduce((prev, curr) => prev + curr, 0),
     [hubReleases]
   );
-
+    console.log('hubReleases', hubReleases)
```
Comment (ejf89) [inline js/hubs/components/HubOverview.js:50]: log

**Review by ejf89 — APPROVED** [review]
