### PR TITLE
Follow fix

### LINKED ISSUE #745: PROFILES / HUB - activeview jumps to first tab after follow / unfollow

### PR DESCRIPTION
**Pull request by ikjudd**
- Closes #745

### CODE REVIEW

File: js/web/components/Profile.js [hunk 1]
```diff
@@ -157,27 +159,28 @@ const Profile = ({ profilePubkey }) => {
...
     }
-
     setViews(updatedView)
   }, [
     profilePublishedReleases,
     profileCollectionReleases,
     profileHubs,
     profileSubscriptionsTo,
     profileSubscriptionsFrom,
+    router.query.view,
```
Comment (ejf89) [inline js/web/components/Profile.js:175]: unused var in dependency array

**Review by ejf89 — APPROVED** [review]
