### PR TITLE
Activeview fix

### LINKED ISSUE #674: WEB - RELEASE: disable hub and collaborator links if none exist

### LINKED ISSUE #717: RELEASE - fix copy on release card for checking collector ownership

### LINKED ISSUE #718: RELEASE - add catalog number

### LINKED ISSUE #720: PROFILE / HUBS - view should stay on activeView after follow handler is called

### PR DESCRIPTION
**Pull request by ikjudd**
- Closes #718 
- Closes #717 
- Closes #674 
- Closes #720

### CODE REVIEW

File: js/web/components/ReleasePurchase.js [hunk 1]
```diff
@@ -274,9 +274,29 @@ const ReleasePurchase = (props) => {
...
+              </Typography>
+              <Typography
+                variant="body2"
+                align="left"
+                gutterBottom
+                cursor="default"
+              >
+                {amountHeld > 0
+                  ? `You own ${
+                      amountHeld > 1 ? `${amountHeld} editions of` : ''
```
Comment (ejf89) [inline js/web/components/ReleasePurchase.js:295]: lets not show anything if user does not own release

File: js/web/components/HubsModal.js [hunk 2]
```diff
@@ -23,54 +23,67 @@ const HubsModal = (props) => {
...
+                    })}
+                </TableBody>
+              </CollectorTable>
+            </StyledPaper>
+          </StyledModal>
+        </Box>
+      ) : (
+        <Box sx={{ cursor: 'pointer' }}>
+          <Cta variant="body2" align="left" paddingBottom="10px">
+            No Hubs
```
Comment (ejf89) [inline js/web/components/HubsModal.js:82]: plz hide if none

File: js/web/components/Profile.js [hunk 3]
```diff
@@ -231,6 +244,16 @@ const Profile = ({ profilePubkey }) => {
     }
   }, [verificationState])
 
+  useEffect(() => {
+    const urlView = window.location.search.substring(
```
Comment (ejf89) [inline js/web/components/Profile.js:248]: remove this, add router to dep array above

**Review by ejf89 — CHANGES_REQUESTED** [review]
see comments

File: js/web/pages/index.js [hunk 4]
```diff
@@ -16,7 +16,7 @@ export default function Home() {
       }
       router.push(path)
     }
-  }, [wallet])
+  }, [wallet, router])
```
Comment (ejf89) [inline js/web/pages/index.js:19]: lets remove this as i dont think we were doing something intentional w the change

File: js/web/pages/profiles/index.js [hunk 5]
```diff
@@ -14,6 +15,6 @@ export default function Profiles() {
       path = '/'
     }
     router.push(path)
-  }, [wallet])
+  }, [wallet, router])
```
Comment (ejf89) [inline js/web/pages/profiles/index.js:18]: think this may be a straggler as well, plz dbl check everything is straigth after removing

**Review by ejf89 — CHANGES_REQUESTED** [review]
plz see comments

**Review by ejf89 — APPROVED** [review]
