### PR TITLE
links in audioplayer point to correct post and release links

### LINKED ISSUE #887: HUBS - link in player redirects to incorrect page

### PR DESCRIPTION
**Pull request by ikjudd**
- Closes #887

### CODE REVIEW

File: js/hubs/components/AudioPlayer.js [hunk 1]
```diff
@@ -119,12 +119,18 @@ const HubAudioPlayer = ({ hubPubkey }) => {
...
+                        href={`/${hubState[track.hub].handle}/${
+                          releaseState.metadata[track.releasePubkey]
+                            .hubPostPubkey
+                            ? 'posts'
+                            : 'releases'
                         }/${
-                          track.hubPostPubkey
-                            ? track.hubPostPubkey
-                            : track.hubReleaseId
+                          releaseState.metadata[track.releasePubkey]
```
Comment (ejf89) [inline js/hubs/components/AudioPlayer.js:128]: `releaseState.metadata[track.releasePubkey]` should be refactored to 1 var as it is repeated 4 times

**Review by ejf89 — CHANGES_REQUESTED** [review]
- seems to still not quite work with tracks that are reposts + i think it causes a new error

**Review by facing-n — APPROVED** [review]
