### PR TITLE
Shared audio component

### LINKED ISSUE #799: WEB - DOMException: The play() request was interrupted by a new load request.
https://developer.chrome.com/blog/play-request-was-interrupted/

### PR DESCRIPTION
**Pull request by facing-n**
closes #799 #798  #763

### CODE REVIEW

File: js/hubs/components/AudioPlayer.js [hunk 1]
```diff
@@ -91,256 +71,101 @@ const AudioPlayer = ({ hubPubkey }) => {
...
-      clearInterval(intervalRef.current)
-    }
-  }, [])
-
   useEffect(() => {
     if (Object.values(tracks).length > 0) {
       const trackValues = Object.values(tracks).sort(
         (a, b) => new Date(b.datetime) - new Date(a.datetime)
       )
+      console.log('trackValues', trackValues)
```
Comment (ejf89) [inline js/hubs/components/AudioPlayer.js:79]: kill log plz

File: js/sdk/src/contexts/Audio/audio.js [hunk 2]
```diff
@@ -219,7 +218,9 @@ const audioPlayerContextHelper = ({
         }
       }
     })
-    setPlaylist([...playlist, ...playlistEntries])
+    console.log('tracks', tracks)
+    console.log('playlistEntries', playlistEntries, playlist)
```
Comment (ejf89) [inline js/sdk/src/contexts/Audio/audio.js:222]: logs

**Review by ejf89 — APPROVED** [review]
plz removed logs

very good refactor +1
