### PR TITLE
Redeem release code fix

### LINKED ISSUE #969: WEB - release code amount input amount is unclear
it isn't clear what this number is doing - input should be cleaned up w/ label so it is very clear what the amount is doing

Image

### LINKED ISSUE #970: SDK - REDEEM CODES - if sold out dont show codes

### PR DESCRIPTION
**Pull request by ikjudd**
- Closes #970 
- Closes #969

### CODE REVIEW

**Comment by ikjudd** [comment]
#969 
- [ ] swapped out `<Input />` for `<TextField />` to accommodate a cleaner looking input label
- [ ] limited input to integers greater than zero

#970 
- [ ] if sold out then don't show Redeem Release Code in web
- [ ] if sold out then don't show RedeemRelease Code in hubs

File: js/sdk/src/components/ReleaseCode.js [hunk 1]
```diff
@@ -11,7 +11,8 @@ import Paper from '@mui/material/Paper'
 import Backdrop from '@mui/material/Backdrop'
 import { styled } from '@mui/material/styles'
 import CloseIcon from '@mui/icons-material/Close'
-import Input from '@mui/material/Input'
+import TextField from '@mui/material/TextField'
+
 const ReleaseCode = ({ release }) => {
   const [codes, setCodes] = useState()
   const [amount, setAmount] = useState(1)
```
Comment (ejf89) [inline js/sdk/src/components/ReleaseCode.js:18]: this should start undefined, not default to one.

File: js/sdk/src/components/ReleaseCode.js [hunk 2]
```diff
@@ -126,13 +127,20 @@ const ReleaseCode = ({ release }) => {
                   padding: '16px 0px',
                 }}
               >
-                <Input
-                  label="ReleaseCode"
+                <TextField
+                  id="standard-number"
```
Comment (ejf89) [inline js/sdk/src/components/ReleaseCode.js:131]: 'Generate Codes' button does not disable when input value is undefied

**Review by ejf89 — APPROVED** [review]
