### PR TITLE
Styling fixes

### LINKED ISSUE #455: Profile - mobile style

### PR DESCRIPTION
**Pull request by ikjudd**
#455 
#499 
#500
#501

### CODE REVIEW

File: js/web/components/Profile.js [hunk 1]
```diff
@@ -475,10 +476,9 @@ const ProfileHeaderWrapper = styled(Box)(({ theme }) => ({
   maxWidth: '100vw',
   [theme.breakpoints.down('md')]: {
     width: '100vw',
-    overflow: 'hidden',
-    textOverflow: 'ellipsis',
-    whiteSpace: 'no-wrap',
-    height: '100px',
+    height: '100%',
+    paddingBottom: '10px',
+    borderBottom: '1px solid #E5E5E5',
```
Comment (ejf89) [inline js/web/components/Profile.js:481]: color should be added to / imported from theme

File: js/web/components/TabHeader.js [hunk 2]
```diff
@@ -128,6 +143,7 @@ const ResponsiveContainer = styled(Box)(({ theme }) => ({
   borderColor: 'divider',
   [theme.breakpoints.down('md')]: {
     maxWidth: '100vw',
+    borderBottom: '1px solid #E5E5E5',
```
Comment (ejf89) [inline js/web/components/TabHeader.js:146]: color import

**Review by ejf89 — CHANGES_REQUESTED** [review]
- plz add some left + right padding to reusable table on mobile
- make sure tabHeaders do not break on to two lines on mobile

File: js/NinaTheme.js [hunk 3]
```diff
@@ -107,6 +107,7 @@ export const NinaTheme = createTheme({
   // },
   spacing: 15,
   maxWidth:'960px',
+  borderBottom: '1px solid #E3E3E3',
```
Comment (ejf89) [inline js/NinaTheme.js:110]: `#E3E3E3` should be added to the colors table so it can be re-used

File: js/web/components/ReusableTable.js [hunk 4]
```diff
@@ -610,13 +611,15 @@ const OverflowContainer = styled(Box)(({ theme }) => ({
...
     minWidth: '0',
+    maxWidth: '20vw',
   },
 }))
 
 const StyledTableDescriptionContainer = styled(Box)(({ theme }) => ({
   overflow: 'hidden',
   textOverflow: 'ellipsis',
   maxWidth: '20vw',
+  [theme.breakpoints.down('md')]: {},
```
Comment (ejf89) [inline js/web/components/ReusableTable.js:622]: remove if unused

File: js/NinaTheme.js [hunk 5]
```diff
@@ -20,6 +20,7 @@ const colors = {
   blueTrans: 'rgba(45, 129, 255, 0.19)',
   pink: '#FF54A6',
   yellow: '#ffe100',
+  borderBottom: '#E3E3E3'
```
Comment (ejf89) [inline js/NinaTheme.js:23]: plz remove

File: js/web/components/ReusableTable.js [hunk 6]
```diff
@@ -564,32 +561,40 @@ const ResponsiveTableContainer = styled(Box)(({ theme }) => ({
   [theme.breakpoints.down('md')]: {
     overflowY: 'unset',
     height: '100% !important',
-    paddingLeft: 0,
+    paddingLeft: '5px',
```
Comment (ejf89) [inline js/web/components/ReusableTable.js:564]: was this supposed to go on the tableCell?

**Review by ejf89 — CHANGES_REQUESTED** [review]
tables are almsot there, plz line uop celldata with header data

**Review by ejf89 — APPROVED** [review]
