### PR TITLE
Search dropdown fix

### LINKED ISSUE #675: WEB - SEARCH: Artists => Accounts

### LINKED ISSUE #725: WEB - REUSEABLE TABLE - app crashes on wallet change
Image

### LINKED ISSUE #726: WEB - AUDIO PLAYER - should click artist name to go to profile

### PR DESCRIPTION
**Pull request by ikjudd**
- Closes #726 
- Closes #725
- Closes #675

### CODE REVIEW

File: js/web/components/AudioPlayer.js [hunk 1]
```diff
@@ -254,7 +253,13 @@ const AudioPlayer = () => {
       <ProgressContainer>
         {track && (
           <ArtistInfo align="left" variant="subtitle1">
-            {track.artist}, <i>{track.title}</i>
+            <Link href={`/hubs/${track.hub}`} passHref>
```
Comment (ejf89) [inline js/web/components/AudioPlayer.js:256]: this will break on tracks that were not published through a hub

**Review by ejf89 — CHANGES_REQUESTED** [review]
plz handle case when release has no hubs

File: js/web/components/AudioPlayer.js [hunk 2]
```diff
@@ -79,6 +81,10 @@ const AudioPlayer = () => {
     [activeIndexRef.current]
   )
 
+  const findTokenAuthority = useMemo(() => {
```
Comment (ejf89) [inline js/web/components/AudioPlayer.js:84]: looks like this isnt being used

**Review by ejf89 — APPROVED** [review]

**Review by ejf89 — APPROVED** [review]

**Review by ejf89 — CHANGES_REQUESTED** [review]
app does not run

**Review by ejf89 — APPROVED** [review]
